spring.application.name=projecte2

# Port del servidor
server.port=8081

# IMPORTANT: Activar l'execució dels scripts SQL
spring.sql.init.mode=always

# SQL logging
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Aquesta línia diu a Spring que, si no es diu el contrari, usi la config local (H2)
spring.profiles.active=local